# NumPy

### 1. 匯入NumPy模組

使用簡寫`np`代替`numpy`是行業內的慣例(Convention)。

In [ ]:
import numpy as np

### 2. 創建`ndarray`

- 可以利用`np.array()`將Python列表(List)轉換為NumPy的`ndarray`。
- 用`type()`檢查，可以發現資料類型是`numpy.ndarray`。
- `ndarray`不能儲存不同資料類型的項目，若強行創建，NumPy會把它們都轉換成字串(String)。
- 用`ndarray.dtype`可以檢查陣列元素的資料類型。
- `np.array()`可以用`dtype`參數指定資料類型，NumPy支援多種資料類型。

[Data Type Objects (dtype)](https://numpy.org/doc/stable/reference/arrays.dtypes.html)

In [ ]:
lst = [1, 2, 3]
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# `ndarray.dtype`
arr.dtype

dtype('int64')

In [ ]:
# Array can't store elements with different types. Numpy will cast them into `str`
arr = np.array([1, "Pyhon", 3, True, 5])
arr

array(['1', 'Pyhon', '3', 'True', '5'], dtype='<U21')

In [ ]:
# `<U21` = `<`: Little Endian, `U`: Unicode, `12`: 12 characters
arr.dtype.type

numpy.str_

In [ ]:
arr = np.array([1.4, 2.3, 3.6])
arr.dtype

dtype('float64')

In [ ]:
arr = np.array([1.4, 2.3, 3.6], dtype="f")
arr.dtype

dtype('float32')

### 3. `ndarray`的基本操作(Operations)

- `ndarray`是一種序列(Sequence)，可以直接用for迴圈跑過每個元素(Element)。
- 新增元素用`np.append(arr, elem)`。
- 插入元素用`np.insert(arr, index, elem)`。
- 更新元素和Python列表(List)一樣，直接用索引值(Index)存取該元素，指定內容(Value)。
- 刪除元素用`np.delete(arr, index)`。
- 新增、插入、刪除事實上都是回傳新的陣列。



In [ ]:
# Loop through a Python list
lst = [1, 2, 3]

for elem in lst:
    print(elem)

1
2
3


In [ ]:
# `ndarray` is a kind of sequence, can be looped through like normal list
arr = np.array([1, 2, 3])

for elem in arr:
    print(elem)

1
2
3


In [ ]:
lst.append(4)
lst

[1, 2, 3, 4]

In [ ]:
# There is no `append()` method for `ndarray`
# arr.append(4)
# arr

In [ ]:
# `np.append(arr, elem)`
np.append(arr, 4)

array([1, 2, 3, 4])

In [ ]:
# `np.insert(arr, index, elem)`
np.insert(arr, 0, 30)

array([30,  1,  2,  3])

In [ ]:
# Update
arr[1] = 10
arr

array([ 1, 10,  3])

In [ ]:
# `np.delete(arr, index)`
np.delete(arr, 0)

array([10,  3])

In [ ]:
# Use `id()` and `ndarray.nbytes` to check size before and after `np.insert()`
arr = np.array([1, 2, 3])

print("Original array id:", id(arr))
print("Original array size:", arr.nbytes)

arr_inserted = np.insert(arr, 0, 30)

print("Array id after insertion:", id(arr_inserted))
print("Array size after insertion:", arr_inserted.nbytes)

Original array id: 140092808145840
Original array size: 24
Array id after insertion: 140092808149296
Array size after insertion: 32


### 4. 形狀(Shape)、維度(Dimension)、大小(Size)
- `ndarray.shape`是陣列每個維度的大小。
- `ndarray.ndim`是陣列的維度。
- `ndarray.size`是陣列中元素的總數。

In [ ]:
# `ndarray.shape`
arr = np.array([1, 2, 3, 4, 5, 6])

arr.shape

(6,)

In [ ]:
# `ndarray.shape` is a tuple
type(arr.shape)

tuple

In [ ]:
# `array.ndim`
arr.ndim

1

In [ ]:
# `arr.size`
arr.size

6

In [ ]:
# Multi-dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.ndim

2

In [ ]:
arr.size

6

### 5. `reshape()`
- `ndarray.reshape()`可以改變陣列的維度，新的形狀(Shape)元素總數要符合，回傳的是陣列的外觀(View)，並不像上面的`np.append()`、`np.insert()`、`np.delete()`會新增一個陣列，改變記憶體位置。
- `ndarray.reshape()`可以用`-1`讓NumPy自己決定該維度大小。

In [ ]:
# `ndarray.reshape()`
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = arr.reshape(3, 2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr.shape

(3, 2)

In [ ]:
# `-1` unknown dimension
arr = arr.reshape(-1, 3)
arr.shape

(2, 3)

In [ ]:
# `ndarray.reshape(-1)` we get column as 1 but rows as unknown
arr = arr.reshape(-1)
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr.shape

(6,)

In [ ]:
arr.ndim

1

In [ ]:
# Reshape to 1 row and unknown columns
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = arr.reshape(1, -1)
arr

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
arr.shape

(1, 6)

In [ ]:
arr.ndim

2

In [ ]:
# Create a NumPy array with shape = (3, 3)
arr = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

arr.shape

(3, 3)

### 6. 廣播(Broadcast)
- 廣播(Broadcast)是NumPy對不同形狀(Shape)的陣列進行數值計算的方式，在Python我們需要使用for迴圈。
- 當操作兩個陣列時，NumPy會逐元素(Element-Wise)比較它們的形狀(shape)，從右到左。
- 當陣列的形狀相同或其中一個維度是$1$時相容(Compatible)。
- NumPy內建一些常見數學運算的函數，例如：`np.sqrt()`、`np.exp()`、`np.log()`、`np.tanh()`。

In [ ]:
# Python list can use `+` to append element
lst = [1, 2, 3]

lst + [4]

[1, 2, 3, 4]

In [ ]:
# `+` for equal shape
arr = np.array([1, 2, 3])

arr + np.array([4, 5, 6])

array([5, 7, 9])

In [ ]:
# `+` when one dimension of them is 1
arr = np.array([1, 2, 3])

arr + np.array([4])

array([5, 6, 7])

In [ ]:
# We need for loop for Python list to achieve element-wise mathematical operations
lst = [1, 2, 3]

# Iterate over the indices and change the element at each index
for i in range(len(lst)):
    lst[i] = lst[i] + 4

lst

[5, 6, 7]

In [ ]:
# `int` is immutable
lst = [1, 2, 3]

for i in lst:
    print(i)
    # This does not work because `int` is immutable in Python
    i = i + 4

# Items remain original
lst

1
2
3


[1, 2, 3]

In [ ]:
# Repetition
lst = [1, 2, 3]

lst * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
# Multiplication
arr = np.array([1, 2, 3])

arr * 2

array([2, 4, 6])

In [ ]:
# Square root
arr = np.array([1, 2, 3])

np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
# Natural Logarithm
arr = np.array([1, 2, 3])

np.log(arr)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
# Exponential
arr = np.array([1, 2, 3])

np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
# Hyperbolic tangent function
arr = np.array([1, 2, 3])

np.tanh(arr)

array([0.76159416, 0.96402758, 0.99505475])

# EXERCISE-3: 二維矩陣乘法(Square Matrix Multiplication)

用暴力法(Brute Force)定義一個函數，計算$2 \times 2$矩陣乘法(Matrix Multiplication)。

In [ ]:
def matrix_multiplication(mat1, mat2):
    
    product = [[0, 0],
               [0, 0]]

    for i in range(len(mat1)):
        for j in range(len(mat2[0])):
            for k in range(len(mat2)):
                product[i][j] += mat1[i][k] * mat2[k][j]

    return product

時間複雜度(Time Complexity): $O(n^{3})$

### 7. 內積(Dot Product)和矩陣乘法(Matrix Multiplication)

- `np.sum()`若`axis=1`才會在同一列(Row)把每行(Column)的元素相加起來。預設值是`axis=0`把同一行(Column)的每列(Row)元素加起來，和Python的`sum()`相同。
- `np.multiply()`和NumPy的`*`一樣，都是逐元素乘法(Element-Wise Multiplication)。
- `np.dot()`和`ndarray.dot()`都是內積(Dot Product)。兩個一維陣列時是內積，兩個二維陣列時和矩陣乘法相同，超過二維不建議使用。純量(Scalar)可以用。
- `np.matmul()`和`@`都是矩陣乘法(Matrix Multiplication)。但不接受純量(Scalar)。

In [ ]:
# `*` for dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Multiply corresponding elements in two vectors and then sum all of the output values
sum(a * b)

32

In [ ]:
# `*` for Matrix Multiplication
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([1, 1, 1])

c * d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Wrong
sum(c * d)

array([5, 7, 9])

In [ ]:
# `np.sum()`
np.sum(c * d, axis=1)

array([ 6, 15])

In [ ]:
# `numpy.multiply()` is another way to perform element-wise matrix multiplication
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Same as `*`
c = np.multiply(a, b)
c

array([ 4, 10, 18])

In [ ]:
# `numpy.dot()`
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)

32

In [ ]:
# `ndarray.dot()`
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a.dot(b)

32

In [ ]:
# `numpy.matmul()`
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([1, 1, 1])

np.matmul(c, d)

array([ 6, 15])

In [ ]:
# `@`
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([1, 1, 1])

c @ d

array([ 6, 15])

### 8. 評測(Benchmark)

比較用Python內建for迴圈實現的內積和NumPy的`dot()`的執行速度。

[Accelerated Linear Algebra Libraries](https://numpy.org/install/#reproducible-installs)


[NumPy C-API](https://numpy.org/doc/stable/reference/c-api/index.html)

In [ ]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += e * f
    return result

# For loop
t0 = datetime.now()
for t in range(T):
    slow_dot_product(a, b)
dt1 = datetime.now() - t0

# `numpy.dot()`
t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 59.6297268907563


# Pandas

### 1. 匯入Pandas模組

使用簡寫`pd`代替`pandas`是行業內的慣例(Convention)。

In [ ]:
import pandas as pd

### 2. 資料讀取(Load)

- 用`pd.read_csv()`讀入CSV檔案(`.csv`)。
- 用`head()`查看數據大致狀況，參數代表列(Row)數。`tail()`用途相仿，只是從資料末端開始。
- 用`info()`能夠看到這個DataFrame簡潔的總結。
- 用`pd.read_excel()`讀入EXCEL活頁簿檔案(`.xlsx`)。

[List of Datasets for ML Research](https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research)

In [ ]:
# Mount the Google drive to Colab
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# `pd.read_csv()`
df = pd.read_csv("drive/My Drive/titanic/train.csv")

In [ ]:
# `df.head()`
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
# Assign number of rows to peek
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [ ]:
# `df.tail()`
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [ ]:
# `df.info()`
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
# `pd.read_excel()`
xlsx = pd.read_excel("drive/My Drive/titanic/train.xlsx")

In [ ]:
xlsx.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# EXERCISE-4: 到網路上找任何你有興趣的數據，用Pandas讀進來

Pandas數據分析比較適合結構化資料(Structured Data)，不過都可以試試看。
- [World Bank Dataset](https://www.kaggle.com/datasets/bhadramohit/world-bank-dataset)
- [Financial Transactions Dataset](https://www.kaggle.com/datasets/computingvictor/transactions-fraud-datasets)
- [Netflix vs Disney](https://www.kaggle.com/datasets/prathamjyotsingh/netflix-vs-disney)
- [VISA Stock Data 2024](https://www.kaggle.com/datasets/umerhaddii/visa-stock-data-2024)
- [Top 12 German Companies Financial Data](https://www.kaggle.com/datasets/heidarmirhajisadati/top-12-german-companies-financial-data)

### 3. DataFrame

`pd.DataFrame()`可以用以下引數(Argument)創建DataFrame:
- 用字典(Dictionary)。
- 用列表(List)。
- 用關鍵字引數(Keyword Argument)`columns`指定行名(Column Name)。
- 用關鍵字引數(Keyword Argument)`index`指定列(Row)的索引標籤(Index Label)。

In [ ]:
# Check the type
type(df)

pandas.core.frame.DataFrame

In [ ]:
# `pd.DataFrame(dict)`
people = {"Name": ["Tom", "Susan", "Mary", "Joe"], "Age": [36, 18, 22, 36]}

pd.DataFrame(people)

Name  Age
0    Tom   36
1  Susan   18
2   Mary   22
3    Joe   36

In [ ]:
# `pd.DataFrame(list)`
pd.DataFrame([1, 2, 3, 4, 5])

0
0  1
1  2
2  3
3  4
4  5

In [ ]:
# `pd.DataFrame(list, columns=list)`
people = [["Tom", 36], ["Susan", 18], ["Mary", 22], ["Joe", 36]]

pd.DataFrame(people, columns=["Name", "Age"])

Name  Age
0    Tom   36
1  Susan   18
2   Mary   22
3    Joe   36

In [ ]:
# `pd.DataFrame(list, columns=list, index=list)`
people = [["Tom", 36], ["Susan", 18], ["Mary", 22], ["Joe", 36]]

pd.DataFrame(people, columns=["Name", "Age"], index=["Zero", "One", "Two", "Three"])

Name  Age
Zero     Tom   36
One    Susan   18
Two     Mary   22
Three    Joe   36

### 4. Series

`pd.Series()`是標籤的一維矩陣(One dimension labeled  array)，可以用如下方法創建:
- 用列表(List)。
- `pd.Series()`用關鍵字引數(Keyword Argument)`columns`指定行(Column)的索引標籤(Index Label)。
- Series沒有支援行名(Column Name)。

In [ ]:
# `pd.Series(list)`
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# `pd.Series(list, index=list)`
s = pd.Series([1, 2, 3, 4, 5], index=["a", "b", "c", "d", "e"])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# Check the type
type(s)

pandas.core.series.Series

In [ ]:
# Get value from index
s["a"]

1

In [ ]:
# Use a list of indexes to get more than one row
s[["a", "d"]]

a    1
d    4
dtype: int64

### 5. 行(Column)與列(Row)的選取

- 行(Column)的選取:
  - `df["column name"]`:用行名(Column Name)選取DataFrame整行(Column)，事實上是回傳Series。
  - `df[list("column name")]`:用多個行名(`[list]`)可以選取DataFrame一部分的行(Column)。
- 列(Row)的選取:
  - `df.iloc[index index]`:用真正的索引值(Index indices)選取列(Row)。
  - `df.loc[index label]`:用索引標籤(Index labels)選取列(Row)。
  - 以上兩個函數都可以用列表(List)當引數(Argument)以取得多列。




In [ ]:
# Series is the data structure for a single column of a DataFrame
type(df["Name"])

pandas.core.series.Series

In [ ]:
df[["Name", "Sex"]]

Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

In [ ]:
type(df[["Name", "Sex"]])

pandas.core.frame.DataFrame

In [ ]:
# Use other dataframe as example
people = [["Tom", 36], ["Susan", 18], ["Mary", 22], ["Joe", 36]]

people_df = pd.DataFrame(people, columns=["Name", "Age"], index=["Zero", "One", "Two", "Three"])
people_df

Name  Age
Zero     Tom   36
One    Susan   18
Two     Mary   22
Three    Joe   36

In [ ]:
# `df.iloc(index indices)` select row
people_df.iloc[0]

Name    Tom
Age      36
Name: Zero, dtype: object

In [ ]:
# `df.loc(index label)` select row
people_df.loc["Zero"]

Name    Tom
Age      36
Name: Zero, dtype: object

In [ ]:
# Select multiple rows
people_df.loc[["Zero", "One"]]

Name  Age
Zero    Tom   36
One   Susan   18

### 6. 資料篩選(Data Filtering):
- `df[conditional expression]`是一個布林(Boolean)的Series，可以用`df[df[conditional expression]]`選取DataFrame的子集(Subset)，結果也是DataFrame。
- `df[df["column name"].isin(list(value))]`:選取符合給定列表(List)裡面值的列(Row)。
- `df[df["column name"].isnull()]`:選取該行(Column)缺值的列(Row)。
- `df[df["column name"].notnull()]`:選取該行(Column)沒缺值的列(Row)。
- `df[df["column name"].between(head, tail)]`:選取該行(Column)的值在某範圍內的列(Row)。

In [ ]:
# Use comparison operators to select
df[df["Age"] < 18]

PassengerId  Survived  Pclass                                     Name  \
7              8         0       3           Palsson, Master. Gosta Leonard   
9             10         1       2      Nasser, Mrs. Nicholas (Adele Achem)   
10            11         1       3          Sandstrom, Miss. Marguerite Rut   
14            15         0       3     Vestrom, Miss. Hulda Amanda Adolfina   
16            17         0       3                     Rice, Master. Eugene   
..           ...       ...     ...                                      ...   
850          851         0       3  Andersson, Master. Sigvard Harald Elias   
852          853         0       3                  Boulos, Miss. Nourelain   
853          854         1       1                Lines, Miss. Mary Conover   
869          870         1       3          Johnson, Master. Harold Theodor   
875          876         1       3         Najib, Miss. Adele Kiamie "Jane"   

        Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
7      male   2.0      3      1    349909  21.0750   NaN        S  
9    female  14.0      1      0    237736  30.0708   NaN        C  
10   female   4.0      1      1   PP 9549  16.7000    G6        S  
14   female  14.0      0      0    350406   7.8542   NaN        S  
16     male   2.0      4      1    382652  29.1250   NaN        Q  
..      ...   ...    ...    ...       ...      ...   ...      ...  
850    male   4.0      4      2    347082  31.2750   NaN        S  
852  female   9.0      1      1      2678  15.2458   NaN        C  
853  female  16.0      0      1  PC 17592  39.4000   D28        S  
869    male   4.0      1      1    347742  11.1333   NaN        S  
875  female  15.0      0      0      2667   7.2250   NaN        C  

[113 rows x 12 columns]

In [ ]:
# Use `==` or `!=` to select
df[df["Name"] == "Jack Dawson"]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [ ]:
df[df["Name"] == "Behr, Mr. Karl Howell"]

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   

     Parch  Ticket  Fare Cabin Embarked  
889      0  111369  30.0  C148        C

In [ ]:
# A series with `True` or `False`
df["Name"] == "Behr, Mr. Karl Howell"

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889     True
890    False
Name: Name, Length: 891, dtype: bool

In [ ]:
# `isin()`
df[df["Embarked"].isin(["S", "Q"])]

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
890          891         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                         Braund, Mr. Owen Harris    male  22.0      1      0   
2                          Heikkinen, Miss. Laina  female  26.0      0      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                        Allen, Mr. William Henry    male  35.0      0      0   
5                                Moran, Mr. James    male   NaN      0      0   
..                                            ...     ...   ...    ...    ...   
885          Rice, Mrs. William (Margaret Norton)  female  39.0      0      5   
886                         Montvila, Rev. Juozas    male  27.0      0      0   
887                  Graham, Miss. Margaret Edith  female  19.0      0      0   
888      Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2   
890                           Dooley, Mr. Patrick    male  32.0      0      0   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500   NaN        S  
2    STON/O2. 3101282   7.9250   NaN        S  
3              113803  53.1000  C123        S  
4              373450   8.0500   NaN        S  
5              330877   8.4583   NaN        Q  
..                ...      ...   ...      ...  
885            382652  29.1250   NaN        Q  
886            211536  13.0000   NaN        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500   NaN        S  
890            370376   7.7500   NaN        Q  

[721 rows x 12 columns]

In [ ]:
# `isnull()`
df[df["Cabin"].isnull()]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
2              3         1       3                    Heikkinen, Miss. Laina   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
5      male   NaN      0      0            330877   8.4583   NaN        Q  
7      male   2.0      3      1            349909  21.0750   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[687 rows x 12 columns]

In [ ]:
# `notnull()`
df[df["Cabin"].notnull()]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[204 rows x 12 columns]

In [ ]:
# `between()`
df[df["Age"].between(18, 60)]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[579 rows x 12 columns]